kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tc-fn-mysql
spec:
  storageClassName: "oci"
  selector:
    matchLabels:
      oci-availability-domain: "US-ASHBURN-AD-1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi