# Default values for Fn
imagePullPolicy: Always

# If non-null, will override the cluster name
nameOverride: ''

fn:
  service:
    port: 80
    type: LoadBalancer
    annotations: {}

fnlb:
  image: fnproject/fnlb
  tag: 0.0.268
  logLevel: info
  resources: {}

fnserver:
  image: fnproject/fnserver
  tag: 0.3.570
  resources: {}
  nodeSelector: {}
  tolerations: []
  env:
    FN_DB_URL: mysql://fnapp:$(FN_DB_PASSWD)@tcp($(FN_DB_HOST):3306)/fndb
    FN_MQ_URL: redis://$(FN_MQ_HOST):6379/
    FN_PORT: 80
    FN_LOG_LEVEL: info
    FN_LOG_DEST: ""
    FN_LOG_PREFIX: ""
    FN_LOGSTORE_URL: ""
    FN_API_CORS_ORIGINS: ""
    FN_API_CORS_HEADERS: ""
    FN_FREEZE_IDLE_MSECS: ""
    FN_EJECT_IDLE_MSECS: ""
    FN_MAX_RESPONSE_SIZE: ""
    FN_RUNNER_API_URL: ""
    FN_RUNNER_ADDRESSES: ""
    FN_NODE_TYPE: ""
    FN_GRPC_PORT: ""
    FN_ZIPKIN_URL: ""
    FN_JAEGER_URL: ""
    FN_NODE_CERT: ""
    FN_NODE_CERT_KEY: ""
    FN_NODE_CERT_AUTHORITY: ""
    FN_PROCESS_COLLECTOR_LIST: ""
    FN_PLACER: ""

ui:
  enabled: true
  fnui:
    image: fnproject/ui
    tag: 0.0.26
    resources: {}
  flowui:
    image: fnproject/flow
    tag: ui
    resources: {}
  service:
    flowuiPort: 3000
    fnuiPort: 80
    type: LoadBalancer
    annotations: {}

flow:
  image: fnproject/flow
  tag: 0.1.83
  logLevel: info
  service:
    port: 80
    type: ClusterIP
    annotations: {}
  resources: {}

##
## MySQL chart configuration
##
mysql:
  persistence:
    enabled: false
    nodeSelector: mysql-storage
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    storageClass: mysql
    accessMode: ReadWriteOnce
    size: 8Gi

  mysqlDatabase: fndb
  mysqlUser: fnapp
  mysqlPassword: boomsauce

##
## Redis chart configuration
##
redis:
  persistence:
    enabled: false
    nodeSelector: redis-storage
    storageClass: redis
    accessMode: ReadWriteOnce
    size: 8Gi
  usePassword: false

## Ingress configuration.
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false

rbac:
  enabled: true
